image: gradle:jdk8

stages:
  - compile
  - test

compile:
  stage: compile
  script:
    - gradle compileJava
  tags:
    - docker
    - java
    - cse373


testcalculator:
  stage: test
  script:
    - gradle test -Dtest.single=TestCalculator
  tags:
    - docker
    - java
    - cse373

testarraydictionary:
  stage: test
  script:
    - gradle test -Dtest.single=TestArrayDictionary
  tags:
    - docker
    - java
    - cse373

testdeletefunctionality:
  stage: test
  script:
    - gradle test -Dtest.single=TestDeleteFunctionality
  tags:
    - docker
    - java
    - cse373


testdeletestress:
  stage: test
  script:
    - gradle test -Dtest.single=TestDeleteStress
  tags:
    - docker
    - java
    - cse373


testdoublelinkedlist:
  stage: test
  script:
    - gradle test -Dtest.single=TestDoubleLinkedList
  tags:
    - docker
    - java
    - cse373


basetest:
  stage: test
  script:
    - gradle test -Dtest.single=BaseTest
  tags:
    - docker
    - java
    - cse373




