image: gradle:jdk8

stages:
  - compile
  - test

compile:
  stage: compile
  script:
    - gradle compileJava
  tags:
    - docker
    - java
    - cse373


test:
  stage: test
  script:
    - gradle test
  tags:
    - docker
    - java
    - cse373
