image: gradle:jdk8

before_script:
  - wget -q https://courses.cs.washington.edu/courses/cse373/18au/files/hw_scripts/hw2-build-gradle -O build.gradle

stages:
  - compile
  - testPart1
  - testPart2

compile:
  stage: compile
  script:
    - wget -q https://courses.cs.washington.edu/courses/cse373/18au/files/hw_scripts/hw2p1-compile.sh
    - sh hw2p1-compile.sh

testPart1:
  stage: testPart1
  script:
    - wget -q https://courses.cs.washington.edu/courses/cse373/18au/files/hw_scripts/hw2p1.sh
    - sh hw2p1.sh
  allow_failure: true


testPart2:
  stage: testPart2
  script:
    - wget -q https://courses.cs.washington.edu/courses/cse373/18au/files/hw_scripts/hw2p2.sh
    - sh hw2p2.sh
  allow_failure: true
