image: gradle:jdk8

stages:
  - compile
  - testPart1
  - testPart2

compile:
  stage: compile
  script:
    - gradle compileJava


testPart1:
  stage: testPart1
  script:
    - gradle test -Dtest.profile=part1
  allow_failure: true

testPart2:
  stage: testPart2
  script:
    - gradle test
  allow_failure: true
